### ISSUE TITLE
Doesnt work yet!!!!

### ISSUE THREAD

**Issue by ghost** [eldond/covfefe#1]
does not work yet, i tried switching my computer on and off but still broken

**Comment by eldond** [comment]
did you try switching your monitor on and off, too? #techsupport

**Comment by eldond** [comment]
okay, but seriously, did you figure out that you have to clone it and then copy it into OMFITdata/modules or whereever OMFIT keeps extra modules?

I tried cloning into OMFITdata/modules, but OMFIT nukes it on export so the git information gets lost.

**Comment by ghost** [comment]
I have not tried to open this module yet, to be honest. I assumed it would be working straight away when I switched branch to this and pulled.
